import Resource, { AllResourcesObject } from "./Resource";

import { Store, StoreItem } from "./Store";
import { Factory } from "./Factory";
import { PacingManager } from "./PacingManager";
import { SaveManager } from "./SaveManager";
import "./Tab.js";
import UIManager from "./UIManager";
import "./styles";
import { Globals } from "./Globals";

const DEV = false;

class Energy extends Resource {
  constructor() {
    super({
      label: "energy",
      initialAmount: 0,
      capacity: 10,
      generateAmount: 1,
      costs: [],
      buildTimeMs: DEV ? 10 : 500,
      buildDescriptions: ["Generating Energy"],
      unitSymbol: { icon: "e", infront: false },
    });
  }
}

class Funds extends Resource {
  constructor() {
    super({
      label: "funds",
      initialAmount: 0,
      generateAmount: 1,
      costs: [{ resource: "energy", amount: 2 }],
      buildTimeMs: DEV ? 1000 : 5000,
      buildDescriptions: ["Analyzing Market", "Executing Plan", "Generating Funds"],
      unitSymbol: { icon: "$", infront: true },
    });
  }
}

const energy = new Energy();
const funds = new Funds();

let resources: AllResourcesObject = { energy, funds };
Factory.ALL_RESOURCES = resources;

let energyFactory = new Factory(energy, JSON.parse(JSON.stringify(funds.costs)), 0);
let fundsFactory = new Factory(funds, JSON.parse(JSON.stringify(funds.costs)), 0);
const pacingManager = new PacingManager(resources);

let store = new Store([
  {
    sortOrder: 1,
    id: "first-purchase",
    collection: "main",
    name: "OS Update",
    description: "Upgrades... Upgrades... Upgrades...",
    costs: [
      { resource: "funds", amount: 2.99 },
      { resource: "energy", amount: 10 },
    ],
    level: 0,
    maxLevel: 1,
    dependsOn: [],
    onPurchase: (self: StoreItem) => {
      pacingManager.showWindow("system");
      pacingManager.showWindow("energy-upgrades");
      pacingManager.showWindow("funds-upgrades");
    },
  },
  {
    sortOrder: 2,
    id: "cosmic-blessing-enable",
    collection: "main",
    name: "Cosmic Blessing",
    description: "Amplifies resource yields in accordance with cosmic alignment (Up to a 35% surge).",
    costs: [
      { resource: "funds", amount: 1000 },
      { resource: "energy", amount: 250 },
    ],
    level: 0,
    maxLevel: 1,
    dependsOn: [["main", "first-purchase", 0]],
    onPurchase: (self: StoreItem) => {
      Globals._maxCosmicBlessing = 0.35;
      pacingManager.showWindow("cosmic-stat");
    },
  },
  {
    sortOrder: 3,
    id: "queue-purchase",
    collection: "main",
    name: "Queues",
    description: `Enables you to schedule up to 2 builds.`,
    costs: [
      { resource: "funds", amount: 50 },
      { resource: "energy", amount: 18 },
    ],
    level: 0,
    maxLevel: 10,
    dependsOn: [["main", "first-purchase", 0]],
    onPurchase: (self: StoreItem) => {
      // Update buildCapacities for all resources
      Object.keys(resources).forEach((resourceKey) => {
        resources[resourceKey].buildQueueCapacity += 1;
      });

      self.costs = self.costs.map((cost) => {
        cost.amount = getChangeAmount(self.level, 1.75, cost.amount, true);
        return cost;
      });

      self.description = `Enables you to schedule up to ${resources["energy"].buildQueueCapacity + 1} builds.`;
    },
  },
  {
    sortOrder: 1,
    id: "funds-generation",
    collection: "funds",
    name: "Funds Generation",
    description: `Increases the amount of funds generated by 100%`,
    costs: [
      { resource: "funds", amount: 1 },
      { resource: "energy", amount: 2 },
    ],
    level: 0,
    dependsOn: [],
    onPurchase: (self: StoreItem) => {
      let startingLevel = 1;
      startingLevel -= self.level * 0.0001;
      startingLevel = startingLevel < 0.1 ? 0.1 : startingLevel; // Cap
      self.description = `Increases the amount of energy generated by ${(startingLevel * 100).toFixed(2)}%`;

      let changeAmount = getChangeAmount(self.level, startingLevel, funds.generateAmount, true);
      funds.generateAmount = changeAmount;
      funds.costs = funds.costs.map((cost) => {
        cost.amount = getChangeAmount(self.level, 0.15, cost.amount, true);
        return cost;
      });

      self.costs = self.costs.map((cost) => {
        cost.amount = getChangeAmount(self.level, 0.15, cost.amount, true);
        return cost;
      });
    },
  },
  {
    sortOrder: 3,
    id: "funds-factory",
    collection: "funds",
    name: "Funds Fabrication",
    description: "Generates Funds Passively",
    costs: [
      { resource: "funds", amount: 10 },
      { resource: "energy", amount: 20 },
    ],
    level: 0,
    maxLevel: 1,
    dependsOn: [["funds", "funds-generation", 3]],
    onPurchase: (self: StoreItem) => {
      fundsFactory.level = 1;
      pacingManager.showWindow("funds-factory");
    },
  },
  {
    sortOrder: 1,
    id: "energy-generation",
    collection: "energy",
    name: "Energy Generation",
    description: `Increases the amount of energy generated by ${(10).toFixed(2)}%`,
    costs: [
      { resource: "funds", amount: 0.5 },
      { resource: "energy", amount: 0.1 },
    ],
    level: 0,
    dependsOn: [],
    onPurchase: (self: StoreItem) => {
      let startingLevel = 0.1;
      startingLevel -= self.level * 0.0001;
      startingLevel = startingLevel < 0.01 ? 0.01 : startingLevel; // Cap

      let changeAmount = getChangeAmount(self.level, startingLevel, energy.generateAmount, true);
      self.description = `Increases the amount of energy generated by ${(startingLevel * 100).toFixed(2)}%`;
      energy.generateAmount = changeAmount;

      self.costs = self.costs.map((cost) => {
        cost.amount = getChangeAmount(self.level, 0.15, cost.amount, true);
        return cost;
      });
    },
  },
  {
    sortOrder: 2,
    id: "energy-capacity",
    collection: "energy",
    name: "Energy Capacity",
    description: `Increase max capacity of energy to ${UIManager.formatValueWithSymbol(getChangeAmount(1, 1, energy.capacity, true), energy.unitSymbol)}`,
    costs: [
      { resource: "funds", amount: 5 },
      { resource: "energy", amount: 9.5 },
    ],
    level: 0,
    dependsOn: [],
    onPurchase: (self: StoreItem) => {
      energy.capacity = getChangeAmount(self.level, 1, energy.capacity, true);

      self.costs = self.costs.map((cost) => {
        cost.amount = getChangeAmount(self.level, 0.95, cost.amount, true);
        return cost;
      });

      self.description = `Increase max capacity of energy to ${UIManager.formatValueWithSymbol(
        getChangeAmount(self.level, 1, energy.capacity, true),
        energy.unitSymbol
      )}`;
    },
  },
  {
    sortOrder: 3,
    id: "energy-factory",
    collection: "energy",
    name: "Energy Fabrication",
    description: "Generates Energy Passively",
    costs: [
      { resource: "funds", amount: 9.5 },
      { resource: "energy", amount: 19.5 },
    ],
    level: 0,
    maxLevel: 1,
    dependsOn: [["energy", "energy-generation", 3]],
    onPurchase: (self: StoreItem) => {
      energyFactory.level = 1;
      pacingManager.showWindow("energy-factory");
    },
  },
]);

// strength: 0-1 value: 1 will reduce by 50% at level 1.
// tension: controls the depth function goes to. tension of 1 will result in 0 change, while 0 will allow the strength to function without restriction.
function getChangeAmount(level: number, strength: number = 0.15, prevNumber: number, up: boolean = true) {
  if (level < 1) {
    throw new Error("Level cannot be 0");
  }

  return (prevNumber / Math.pow(up ? 1 + strength : 1 - strength, level - 1)) * Math.pow(up ? 1 + strength : 1 - strength, level);
}

new SaveManager(resources, pacingManager, store, { fundsFactory, energyFactory });

Globals.initCosmicBlessing(resources);

// DEV!!!! ---------------------------------------------------------------
let clickCount = 0;
let lastClickTime = 0;

document.getElementById("dev-hard-reset").addEventListener("click", function () {
  const currentTime = new Date().getTime();

  // Check if it's a triple click within 1 second
  if (currentTime - lastClickTime < 1000) {
    clickCount++;
    if (clickCount === 3) {
      localStorage.clear();

      // Reload the page
      location.reload();
    }
  } else {
    clickCount = 1;
  }

  lastClickTime = currentTime;
});

document.addEventListener("DOMContentLoaded", function () {
  document.querySelectorAll('button[aria-label="Minimize"]').forEach((helpButton) => {
    helpButton.addEventListener("click", function () {
      // Get the target id from the data-target attribute
      var targetId = this.getAttribute("data-target");

      // Get the corresponding help text element
      var helpText = document.getElementById(targetId);

      // Toggle the visibility of the help text
      if (helpText) {
        helpText.style.display = helpText.style.display === "block" || helpText.style.display === "" ? "none" : "block";
      }
    });
  });
});
